name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Link to local cargo
      run: ln -s `which cargo`
    - name: Lint
      run: make lint
    - name: Fmt check. `make fmt` and push, if failed
      run: make fmt-check
    - name: Run tests
      run: make test
